-- MySQL Script generated by MySQL Workbench
-- Thu Feb 13 20:13:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Team9RMDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Team9RMDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Team9RMDB` DEFAULT CHARACTER SET utf8 ;
USE `Team9RMDB` ;

-- -----------------------------------------------------
-- Table `Team9RMDB`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Category` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Category` (
  `CategoryName` VARCHAR(20) NOT NULL,
  `SubCategoryName` VARCHAR(20) NULL DEFAULT NULL,
  `Description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CategoryName`),
  INDEX `SubCategoryName_idx` (`SubCategoryName` ASC) VISIBLE,
  CONSTRAINT `SubCategoryName`
    FOREIGN KEY (`SubCategoryName`)
    REFERENCES `Team9RMDB`.`Category` (`CategoryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Customer` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Customer` (
  `CustomerID` INT NOT NULL,
  `First_Name` VARCHAR(20) NOT NULL,
  `Last_Name` VARCHAR(20) NOT NULL,
  `Ship_Address` VARCHAR(40) NOT NULL,
  `Ship_City` VARCHAR(20) NULL DEFAULT NULL,
  `Ship_State` VARCHAR(2) NULL DEFAULT NULL,
  `Ship_Zip` VARCHAR(9) NULL DEFAULT NULL,
  `Bill_Address` VARCHAR(40) NOT NULL,
  `Bill_City` VARCHAR(20) NULL DEFAULT NULL,
  `Bill_State` VARCHAR(2) NULL DEFAULT NULL,
  `Bill_Zip` VARCHAR(9) NULL DEFAULT NULL,
  `Phone` VARCHAR(11) NULL DEFAULT NULL,
  `Email` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`CustomerID`));


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Customer_Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Customer_Transactions` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Customer_Transactions` (
  `CustomerID` INT NOT NULL,
  `TransactionID` INT NOT NULL,
  INDEX `CustomerID_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `TransactionID_idx` (`TransactionID` ASC) VISIBLE,
  CONSTRAINT `CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `Team9RMDB`.`Customer` (`CustomerID`),
  CONSTRAINT `TransactionID`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `Team9RMDB`.`Transactions` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Employee` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Employee` (
  `EmployeeID` INT NOT NULL,
  `First_Name` VARCHAR(20) NOT NULL,
  `Last_Name` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(40) NOT NULL,
  `City` VARCHAR(20) NULL DEFAULT NULL,
  `State` VARCHAR(2) NULL DEFAULT NULL,
  `Zip` VARCHAR(9) NULL DEFAULT NULL,
  `Salary` DECIMAL(10,2) NOT NULL,
  `S_ID` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`),
  INDEX `StoreID_idx` (`S_ID` ASC) VISIBLE,
  CONSTRAINT `StoreID`
    FOREIGN KEY (`S_ID`)
    REFERENCES `Team9RMDB`.`Store_Location` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Employee_Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Employee_Transactions` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Employee_Transactions` (
  `EmployeeID` INT NOT NULL,
  `TransactionID` INT NOT NULL,
  INDEX (`EmployeeID` ASC) VISIBLE,
  INDEX `TransactionID_idx` (`TransactionID` ASC) VISIBLE,
  CONSTRAINT `EmployeeID`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `Team9RMDB`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TransactionID`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `Team9RMDB`.`Transactions` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Inventory` (
  `StoreID` INT NOT NULL,
  `InventoryID` INT NOT NULL,
  `Stock` INT NOT NULL,
  `CategoryName` VARCHAR(20) NOT NULL,
  `ProductID` INT NOT NULL,
  `TransactionID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`StoreID`, `InventoryID`),
  INDEX `CategoryName_idx` (`CategoryName` ASC) VISIBLE,
  INDEX `ProductID_idx` (`ProductID` ASC) VISIBLE,
  INDEX `TransactionID_idx` (`TransactionID` ASC) VISIBLE,
  CONSTRAINT `CategoryName`
    FOREIGN KEY (`CategoryName`)
    REFERENCES `Team9RMDB`.`Category` (`CategoryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProductID`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Team9RMDB`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TransactionID`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `Team9RMDB`.`Transactions` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StoreID`
    FOREIGN KEY (`StoreID`)
    REFERENCES `Team9RMDB`.`Store_Location` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Orders` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Orders` (
  `OrderID` INT NOT NULL,
  `Order_Date` DATETIME NOT NULL,
  `Ship_Date` DATETIME NULL DEFAULT NULL,
  `Quantity` INT NULL DEFAULT NULL,
  `Total` DECIMAL(6,2) NOT NULL,
  `V_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `V_ID_idx` (`V_id` ASC) VISIBLE,
  CONSTRAINT `V_ID`
    FOREIGN KEY (`V_id`)
    REFERENCES `Team9RMDB`.`Vendor` (`VendorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Product` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Product` (
  `CategoryName` VARCHAR(20) NOT NULL,
  `ProductID` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Description` VARCHAR(50) NOT NULL,
  `Price` DECIMAL(6,2) NOT NULL,
  `Quantity` INT NOT NULL,
  `StoreID` INT NOT NULL,
  `InventoryID` INT NOT NULL,
  PRIMARY KEY (`CategoryName`, `ProductID`),
  INDEX `InventoryID_idx` (`InventoryID` ASC) VISIBLE,
  INDEX `StoreID_idx` (`StoreID` ASC) VISIBLE,
  CONSTRAINT `CategoryName`
    FOREIGN KEY (`CategoryName`)
    REFERENCES `Team9RMDB`.`Category` (`CategoryName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StoreID`
    FOREIGN KEY (`StoreID`)
    REFERENCES `Team9RMDB`.`Product` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InventoryID`
    FOREIGN KEY (`InventoryID`)
    REFERENCES `Team9RMDB`.`Inventory` (`InventoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Products_Ordered`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Products_Ordered` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Products_Ordered` (
  `ProductID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `ProductID_idx` (`ProductID` ASC) VISIBLE,
  CONSTRAINT `ProductID`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Team9RMDB`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderID`
    FOREIGN KEY (`OrderID`)
    REFERENCES `Team9RMDB`.`Orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Store_Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Store_Location` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Store_Location` (
  `StoreID` INT NOT NULL,
  `Address` VARCHAR(40) NOT NULL,
  `City` VARCHAR(20) NULL DEFAULT NULL,
  `State` VARCHAR(2) NULL DEFAULT NULL,
  `Zip` VARCHAR(9) NULL DEFAULT NULL,
  PRIMARY KEY (`StoreID`));


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Store_Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Store_Transactions` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Store_Transactions` (
  `StoreID` INT NOT NULL,
  `TransactionID` INT NOT NULL,
  INDEX `StoreID` (`StoreID` ASC) VISIBLE,
  INDEX `TransactionID_idx` (`TransactionID` ASC) VISIBLE,
  CONSTRAINT `StoreID`
    FOREIGN KEY (`StoreID`)
    REFERENCES `Team9RMDB`.`Store_Location` (`StoreID`),
  CONSTRAINT `TransactionID`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `Team9RMDB`.`Transactions` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Transactions` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Transactions` (
  `TransactionID` INT NOT NULL,
  `Order_Date` DATETIME NOT NULL,
  `Ship_Date` DATETIME NULL DEFAULT NULL,
  `Quantity` INT NULL DEFAULT NULL,
  `Total` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`TransactionID`));


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Vendor` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Vendor` (
  `VendorID` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Phone` VARCHAR(11) NULL DEFAULT NULL,
  `Email` VARCHAR(20) NULL DEFAULT NULL,
  `Street_Address` VARCHAR(40) NOT NULL,
  `City` VARCHAR(20) NULL DEFAULT NULL,
  `State` VARCHAR(2) NULL DEFAULT NULL,
  `Zip` VARCHAR(9) NULL DEFAULT NULL,
  PRIMARY KEY (`VendorID`),
  CONSTRAINT `VendorID`
    FOREIGN KEY ()
    REFERENCES `Team9RMDB`.`Vendor` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Team9RMDB`.`Vendor_Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team9RMDB`.`Vendor_Orders` ;

CREATE TABLE IF NOT EXISTS `Team9RMDB`.`Vendor_Orders` (
  `VendorID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  INDEX `VendorID` (`VendorID` ASC) VISIBLE,
  INDEX `OrderID_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `VendorID`
    FOREIGN KEY (`VendorID`)
    REFERENCES `Team9RMDB`.`Vendor` (`VendorID`),
  CONSTRAINT `OrderID`
    FOREIGN KEY (`OrderID`)
    REFERENCES `Team9RMDB`.`Orders` (`OrderID`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
